steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'run'
  entrypoint: 'bash'
  args:
    [
      '-c',
      # privileged and security-opts are needed to run Docker-in-Docker
      # https://rootlesscontaine.rs/getting-started/common/apparmor/
      'docker run --privileged --security-opt seccomp=unconfined --security-opt apparmor=unconfined -eENCODED_JIT_CONFIG=$_ENCODED_JIT_CONFIG $LOCATION-docker.pkg.dev/$PROJECT_ID/$_CONTAINER_REPOSITORY/github-actions-runner:latest'
    ]
  automapSubstitutions: true
options:
  logging: 'CLOUD_LOGGING_ONLY'
